import { JOURNEY } from "@/components/cs-journey/journeyData";
import type { Track, TrackChapter } from "@/types/schema";

export const PALETTES = [
  { g1: "#fef9c3", g2: "#fde68a", g3: "#f59e0b", accent: "#92400e" }, // amber
  { g1: "#eff6ff", g2: "#93c5fd", g3: "#3b82f6", accent: "#1e40af" }, // blue
  { g1: "#f0fdfa", g2: "#5eead4", g3: "#0d9488", accent: "#134e4a" }, // teal
  { g1: "#fdf4ff", g2: "#d8b4fe", g3: "#9333ea", accent: "#581c87" }, // purple
  { g1: "#fff7ed", g2: "#fdba74", g3: "#ea580c", accent: "#7c2d12" }, // orange
  { g1: "#fff1f2", g2: "#fda4af", g3: "#e11d48", accent: "#881337" }, // rose
  { g1: "#f5f3ff", g2: "#c4b5fd", g3: "#7c3aed", accent: "#4c1d95" }, // violet
  { g1: "#f0fdf4", g2: "#86efac", g3: "#16a34a", accent: "#14532d" }, // emerald
] as const;

export function chapter(
  trackId: string,
  num: number,
  title: string,
  sub: string,
  desc: string,
  tags: string[],
  body: string
): TrackChapter {
  const p = PALETTES[(num - 1) % PALETTES.length];
  return {
    id: `${trackId}-${num}`,
    num: String(num).padStart(2, "0"),
    title,
    sub,
    desc,
    tags,
    body,
    ...p,
  };
}

export function buildTrack(
  id: string,
  title: string,
  tagline: string,
  chapters: TrackChapter[],
  ownerId: string | null = null,
  source: Track["source"] = "builtin",
  rawNotes: string | null = null
): Track {
  return {
    id,
    title,
    tagline,
    accentColor: chapters[0]?.g3 ?? "#f59e0b",
    source,
    ownerId,
    rawNotes,
    createdAt: "2026-01-01T00:00:00.000Z",
    chapters,
  };
}

// ── Python Fundamentals for DSA — reuses the hand-illustrated chapters ──────
const PYTHON_FUNDAMENTALS_BODIES = [
  "Every program starts with storing and naming information. A variable is a label pointing at a value in memory — `x = 42` doesn't just set `x`, it tells Python to create an integer object and bind the name `x` to it. Python is dynamically typed: the same name can point at an int, then a string, then a list, with no declaration required. Learn the core primitive types (`int`, `float`, `str`, `bool`), how `input()` and `print()` move data in and out of your program, and how expressions like `score * 2 + 1` get evaluated left to right by operator precedence. Get comfortable with f-strings (`f\"{name} scored {score}\"`) early — you'll use them constantly.",
  "Programs that only run top-to-bottom can't react to anything. `if`/`elif`/`else` blocks let your code branch based on a condition, and conditions are just expressions that evaluate to `True` or `False`. Comparison operators (`==`, `!=`, `<`, `>=`) build the conditions; `and`/`or`/`not` combine them. The single biggest beginner trap is confusing `=` (assignment) with `==` (comparison) — Python won't let you do it inside an `if`, but the habit matters for every language after this one. Practice nesting conditions and, just as importantly, practice *flattening* them — deeply nested if/else is usually a sign you can restructure with early returns.",
  "Loops are how a few lines of code do thousands of repetitions. `for` loops iterate over a known sequence (`for i in range(10)`, `for char in \"hello\"`); `while` loops repeat as long as a condition holds, which is what you want when you don't know the iteration count in advance (reading input until the user quits, searching until found). Learn `break` to exit early and `continue` to skip an iteration, and watch for the classic `while` bug: forgetting to update the condition variable, which spins forever. Nested loops (a loop inside a loop) are how you process grids and pairs — they're also where naive solutions get slow, a preview of Big-O thinking later in DSA.",
  "Functions are how you stop repeating yourself. `def greet(name): return f\"Hi {name}\"` packages logic behind a name you can call from anywhere, with parameters that make it reusable for different inputs. Understand the difference between *parameters* (the placeholders in the definition) and *arguments* (the real values you pass in), default arguments, and what a function returns when there's no explicit `return` (`None`). Pair this with Python's core collections — `list` for ordered, mutable sequences and `str` for immutable text — and their slicing syntax (`items[1:3]`, `name[::-1]`). Mastering list comprehensions (`[x*2 for x in items if x > 0]`) here will make every DSA problem you write afterward shorter and clearer.",
  "Lists get you far, but real data is rarely flat. Dictionaries (`{\"name\": \"Alice\", \"age\": 30}`) map keys to values in O(1) average lookup time — this is the single most important data structure for DSA interviews after arrays, because so many problems reduce to \"have I seen this before\" (use a dict or set). Tuples are like lists but immutable, which makes them safe to use as dict keys or to return multiple values from a function (`return min_val, max_val`). File I/O (`open(\"data.txt\") as f`) is how programs persist data beyond a single run — learn the `with` statement, which guarantees the file closes even if an error occurs partway through.",
  "Object-oriented programming lets you bundle data and the behavior that acts on it into one unit. A `class` is a blueprint; an *instance* (`dog1 = Dog()`) is a concrete object built from it. `self` refers to the specific instance a method is called on — it's how `dog1.bark()` and `dog2.bark()` can share one method definition but act on different data. Learn the constructor (`__init__`), instance attributes (`self.name = name`), and inheritance, where a subclass (`class Dog(Animal)`) reuses and extends a parent's behavior. You won't need heavy OOP for most DSA problems, but it's essential once you're organizing real applications instead of single-function scripts.",
  "This is where the pieces come together. Modules (`import random`, `import math`) let you pull in code other people wrote instead of reinventing it — and your own files can be imported the same way, which is how real projects are organized across many files instead of one giant script. Recursion is a function that calls itself with a smaller version of the problem until it hits a base case (`if n == 0: return 1`) — it's the foundation for tree traversal, divide-and-conquer, and a huge fraction of classic DSA problems. From here, the path forward is applying all of this to actual algorithms: sorting, searching, and the data structures (stacks, queues, trees, graphs) that the rest of your DSA prep will build on.",
];

const PYTHON_FUNDAMENTALS_TRACK: Track = buildTrack(
  "python-fundamentals-dsa",
  "Python Fundamentals for DSA",
  "The Python you need before data structures & algorithms.",
  JOURNEY.map((ch, i) =>
    chapter(
      "python-fundamentals-dsa",
      i + 1,
      ch.title,
      ch.sub,
      ch.desc,
      ch.tags,
      PYTHON_FUNDAMENTALS_BODIES[i]
    )
  )
);

// ── Python for AI ────────────────────────────────────────────────────────────
const PYTHON_FOR_AI_TRACK: Track = buildTrack(
  "python-for-ai",
  "Python for AI",
  "The applied-math-to-code path from arrays to language models.",
  [
    chapter(
      "python-for-ai",
      1,
      "NumPy & Vectorized Thinking",
      "Arrays, not loops",
      "AI code lives or dies on arrays. NumPy gives you the `ndarray`, and the mental shift from \"loop over elements\" to \"operate on the whole array at once\" is the single most important habit you'll build here.",
      ["NumPy", "Arrays", "Broadcasting"],
      "Almost every AI library — Pandas, scikit-learn, PyTorch — is built on the same idea NumPy introduced: store numbers in contiguous arrays and operate on entire arrays at once instead of writing Python-level `for` loops, which are slow. `a + b` adds two arrays element-wise; `a @ b` does matrix multiplication. Learn shapes (`(3, 4)` means 3 rows, 4 columns) and broadcasting — NumPy's rule for combining arrays of different shapes (e.g. adding a single row to every row of a matrix) without writing explicit loops. Index with slices (`a[:, 0]` for the first column) and boolean masks (`a[a > 0]` for all positive values) — you'll use both constantly when cleaning data before it reaches a model.",
    ),
    chapter(
      "python-for-ai",
      2,
      "Pandas for Data Wrangling",
      "Real data is messy",
      "Real-world data has missing values, wrong types, and duplicate rows. Pandas' DataFrame is the standard tool for loading, cleaning, and reshaping tabular data before anything touches a model.",
      ["Pandas", "DataFrames", "Cleaning"],
      "A `DataFrame` is a table — rows and named columns, built on top of NumPy arrays underneath. `pd.read_csv(\"data.csv\")` loads a file in one line; `df.head()`, `df.info()`, and `df.describe()` are your first three commands on any new dataset, giving you a shape, types, and missing-value count before you do anything else. Learn `df[df[\"age\"] > 18]` for filtering, `df.groupby(\"category\").mean()` for aggregation, and `df.dropna()` / `df.fillna()` for handling missing data — a decision that quietly determines how good your downstream model can be. Merging datasets (`pd.merge`) and reshaping (`pivot_table`) round out the toolkit you'll reach for in almost every AI project's first hour.",
    ),
    chapter(
      "python-for-ai",
      3,
      "Visualizing Data with Matplotlib",
      "See it before you model it",
      "You can't trust a model on data you haven't looked at. A handful of plot types — histograms, scatter plots, line charts — catch more data problems than any amount of staring at numbers.",
      ["Matplotlib", "Plots", "EDA"],
      "Before training anything, plot the data. A histogram (`plt.hist(df[\"price\"])`) reveals skew and outliers in one glance; a scatter plot (`plt.scatter(x, y)`) shows whether two variables actually relate to each other before you assume a model will find a pattern that isn't there. Learn the basic Matplotlib API — figures, axes, `plt.plot`/`plt.scatter`/`plt.hist`, labels and titles — and when to reach for Pandas' built-in `.plot()` shortcut versus Matplotlib directly. This step is called exploratory data analysis (EDA), and skilled practitioners spend a surprising amount of time here: most \"the model isn't learning\" bugs trace back to a data problem a plot would have caught in seconds.",
    ),
    chapter(
      "python-for-ai",
      4,
      "Intro to Machine Learning with scikit-learn",
      "Fit, predict, evaluate",
      "Every scikit-learn model follows the same three-method contract: fit, predict, score. Once that clicks, swapping a linear regression for a random forest is a one-line change.",
      ["scikit-learn", "Regression", "Classification"],
      "scikit-learn standardizes machine learning behind one interface: `model.fit(X_train, y_train)` trains it, `model.predict(X_test)` makes predictions, and `model.score(X_test, y_test)` evaluates it. Learn the train/test split (`train_test_split`) and why you never evaluate on data the model trained on — that number lies to you. Start with two model families: linear/logistic regression for a baseline you can reason about, and a tree-based model (`RandomForestClassifier`) for something stronger with minimal tuning. Understand the difference between regression (predicting a number, like a price) and classification (predicting a category, like spam/not-spam) — it determines which model family and which metric (accuracy vs. mean squared error) you reach for.",
    ),
    chapter(
      "python-for-ai",
      5,
      "Neural Network Foundations",
      "From weights to gradients",
      "A neural network is layers of weighted sums and nonlinear functions, trained by nudging every weight slightly downhill on a loss curve, millions of times, via backpropagation.",
      ["Neural Networks", "PyTorch", "Backprop"],
      "Strip away the hype and a neural network is a stack of layers, each doing `output = activation(weights @ input + bias)`. The \"learning\" is gradient descent: compute how wrong the output was (the loss), then use backpropagation — repeated chain-rule differentiation — to figure out how much each weight contributed to that error, and nudge it slightly in the direction that reduces it. Frameworks like PyTorch automate the calculus (`loss.backward()` computes every gradient for you) so you focus on architecture instead of derivatives by hand. Build your first network on something small and well-understood (digit classification on MNIST) before reaching for anything bigger — the workflow (forward pass, loss, backward pass, optimizer step) is identical whether the network has 3 layers or 300.",
    ),
    chapter(
      "python-for-ai",
      6,
      "Working with LLM APIs",
      "Prompting as a skill",
      "Modern AI products are increasingly built by calling a hosted model through an API, not training one from scratch. Structuring prompts and parsing responses reliably is its own skill.",
      ["LLM APIs", "Prompting", "JSON Output"],
      "A large fraction of real AI applications today never train a model — they send a well-structured prompt to a hosted API (OpenAI, Anthropic, or free alternatives) and use the response. Learn the request shape: a `messages` array with `system`/`user`/`assistant` roles, and parameters like `temperature` (higher = more random) and `max_tokens` (response length cap). The hard part isn't the API call — it's getting structured, parseable output back. Instructing the model explicitly to return JSON, giving it a schema to follow, and writing defensive parsing code (the model will occasionally wrap JSON in prose or markdown fences despite instructions) is the difference between a demo and something you can ship.",
    ),
  ]
);

// ── Web Fundamentals ──────────────────────────────────────────────────────────
const WEB_FUNDAMENTALS_TRACK: Track = buildTrack(
  "web-fundamentals",
  "Web Fundamentals",
  "HTML, CSS, and JavaScript — how a webpage actually works.",
  [
    chapter("web-fundamentals", 1, "HTML: Structure & Semantics", "The skeleton", "Every webpage is a tree of elements. Semantic tags (`<nav>`, `<article>`, `<button>`) describe meaning, not just appearance — and that meaning is what screen readers and search engines rely on.", ["HTML", "DOM", "Semantics"], "HTML describes structure: a `<h1>` is a heading regardless of how it's styled, a `<button>` is clickable and keyboard-focusable by default in a way a styled `<div>` never automatically is. Learn the document tree (the DOM) that the browser builds from your markup, and prefer semantic elements (`<nav>`, `<header>`, `<main>`, `<article>`) over generic `<div>`s wherever one fits — it costs nothing and pays off in accessibility and SEO. Forms (`<input>`, `<select>`, `<form>`) are how users send data back to a server; understand `name` attributes and the difference between `GET` and `POST` submission before you touch any framework."),
    chapter("web-fundamentals", 2, "CSS: Layout & the Box Model", "Making it look right", "Every element is a box with content, padding, border, and margin. Flexbox and Grid are the two layout systems that replaced two decades of float-based hacks.", ["CSS", "Flexbox", "Grid"], "Every HTML element renders as a box: content, surrounded by padding, then a border, then margin — get this model wrong and every size calculation you make will be wrong too. `display: flex` turns a container into a one-dimensional layout (row or column) where children can grow, shrink, and align with a handful of properties (`justify-content`, `align-items`, `gap`); `display: grid` does the same for two-dimensional layouts with explicit rows and columns. Learn the cascade and specificity — why two conflicting rules resolve the way they do — before reaching for `!important`, which is almost always a sign the underlying selector structure needs fixing instead."),
    chapter("web-fundamentals", 3, "JavaScript & the DOM", "Making it interactive", "JavaScript is how a static page becomes an app: reading and writing the DOM, and reacting to events like clicks and keystrokes.", ["JavaScript", "Events", "DOM Manipulation"], "JavaScript runs in the browser and can read and modify the DOM the HTML produced — `document.querySelector(\".btn\")` finds an element, `.textContent = \"...\"` changes what it shows, `.addEventListener(\"click\", fn)` reacts when a user interacts with it. Learn variables (`let`/`const`), functions, and array methods (`map`, `filter`, `reduce`) — they're used constantly in real frontend code. Understand that the DOM and JavaScript's event loop are single-threaded: long-running code blocks the page from responding, which is why slow operations (network requests, heavy computation) need to be asynchronous instead of blocking."),
    chapter("web-fundamentals", 4, "Async JavaScript & Fetching Data", "Talking to a server", "Network requests take time and shouldn't freeze the page. Promises and `async`/`await` are how modern JavaScript handles that without callback spaghetti.", ["Fetch API", "Promises", "async/await"], "`fetch(\"/api/users\")` sends a network request and immediately returns a `Promise` — an object representing a value that isn't ready yet. `await` (inside an `async` function) pauses that function specifically until the promise resolves, without blocking the rest of the page. Learn the standard pattern: `const res = await fetch(url); const data = await res.json();`, plus `try`/`catch` for handling network failures, which happen far more often in production than in a tutorial. Understanding promises is the single biggest unlock for reading modern JavaScript code — almost everything that touches a network or a file is promise-based."),
    chapter("web-fundamentals", 5, "Browser Basics: HTTP, Storage & Dev Tools", "What's actually happening", "Every page load is an HTTP request/response cycle. Understanding status codes, headers, and browser storage demystifies almost every \"why isn't this working\" bug.", ["HTTP", "localStorage", "DevTools"], "When you type a URL, the browser sends an HTTP request and the server sends back a response with a status code (`200` ok, `404` not found, `500` server error) and a body. Learn to read the Network tab in browser DevTools — it shows every request a page makes, with timing, headers, and response bodies, and is the first place to look when something isn't loading correctly. `localStorage` persists small amounts of data in the browser across sessions (this whole app's data layer uses it); cookies are similar but get sent automatically with every request to the same domain, which is how login sessions traditionally work."),
  ]
);

// ── Data Structures Visualized ────────────────────────────────────────────────
const DATA_STRUCTURES_TRACK: Track = buildTrack(
  "data-structures-visualized",
  "Data Structures Visualized",
  "Arrays, stacks, trees, and graphs — what they are and when to reach for each.",
  [
    chapter("data-structures-visualized", 1, "Arrays & Strings", "Contiguous memory", "An array is a block of memory where every element sits at a predictable offset — that's what makes index access O(1) and insertion in the middle O(n).", ["Arrays", "Strings", "Two Pointers"], "An array stores elements contiguously in memory, so `arr[i]` is a single calculated offset away — O(1) access, regardless of array size. The cost shows up on insertion/deletion in the middle: every element after the gap has to shift, making that O(n). Strings behave like arrays of characters and share the same trade-offs. The two-pointer technique (one pointer at each end, moving inward) is the single most common pattern for array/string problems — sorted-array searches, palindrome checks, and reversing all reduce to it."),
    chapter("data-structures-visualized", 2, "Stacks & Queues", "Order of removal", "A stack removes the most recently added item first (LIFO); a queue removes the oldest item first (FIFO). The same data, two completely different access patterns.", ["Stacks", "Queues", "LIFO/FIFO"], "A stack supports `push` and `pop` from one end only — last in, first out (LIFO), like a stack of plates. It's the structure behind function call frames (which is why deep recursion causes a \"stack overflow\") and behind matching-bracket / undo-history problems. A queue supports adding at one end and removing from the other — first in, first out (FIFO) — and is the natural structure for anything processed in arrival order, like a print queue or breadth-first traversal. Both can be implemented on top of an array or a linked list; knowing which operations need to be fast determines which underlying implementation you pick."),
    chapter("data-structures-visualized", 3, "Linked Lists", "Pointers, not indices", "A linked list trades O(1) random access for O(1) insertion anywhere — each node just points to the next, with no shifting required.", ["Linked Lists", "Pointers", "Traversal"], "Unlike an array, a linked list's elements (\"nodes\") aren't contiguous — each node holds a value and a pointer to the next node. That means there's no `arr[i]` shortcut (finding the i-th element means walking from the head, O(n)), but inserting or deleting a node only requires updating a couple of pointers, no shifting. Learn to draw these out by hand — most linked-list bugs come from losing track of a pointer mid-update — and practice the classic patterns: reversing a list in place, detecting a cycle with two pointers moving at different speeds (Floyd's algorithm), and merging two sorted lists."),
    chapter("data-structures-visualized", 4, "Trees & Binary Search Trees", "Hierarchies", "A tree is a hierarchy of nodes with no cycles. A binary search tree adds an ordering rule that makes search, insert, and delete all O(log n) on average.", ["Trees", "BST", "Traversal"], "A tree is a graph with no cycles, organized into parent/child relationships starting from a root. A binary search tree (BST) adds one rule: every left subtree holds smaller values, every right subtree holds larger ones — which makes lookup a repeated halving of the search space, O(log n) on a balanced tree. Learn the three depth-first traversal orders (in-order, pre-order, post-order) and breadth-first (level-order) traversal — almost every tree problem is a variation of one of these four walks, usually written recursively."),
    chapter("data-structures-visualized", 5, "Graphs & Traversal", "Anything connected to anything", "A graph generalizes a tree: any node can connect to any other, including cycles. BFS and DFS are the two ways to systematically visit every reachable node.", ["Graphs", "BFS", "DFS"], "A graph is nodes (vertices) connected by edges, with no restriction on structure — social networks, maps, and dependency chains are all graphs. Depth-first search (DFS) explores as far as possible down one path before backtracking, usually implemented with recursion or an explicit stack; breadth-first search (BFS) explores level by level using a queue, and is the standard way to find the shortest path in an unweighted graph. Learn to represent a graph as an adjacency list (a map from each node to its neighbors) — it's the representation almost every real implementation uses, and the one that makes both traversals straightforward to code."),
  ]
);

// ── Algorithms Deep Dive ──────────────────────────────────────────────────────
const ALGORITHMS_TRACK: Track = buildTrack(
  "algorithms-deep-dive",
  "Algorithms Deep Dive",
  "Sorting, searching, and the complexity analysis to reason about both.",
  [
    chapter("algorithms-deep-dive", 1, "Big-O & Complexity Analysis", "How to measure 'fast'", "Big-O describes how an algorithm's runtime grows as input grows — not the exact speed, but the shape of the curve. It's the language every algorithm discussion runs on.", ["Big-O", "Time Complexity", "Space Complexity"], "Big-O notation describes how runtime (or memory) scales as input size `n` grows, ignoring constant factors and lower-order terms — O(n) means roughly linear growth, O(n²) means a nested loop over the input, O(log n) means the problem halves each step. Two algorithms can both be \"correct\" but one degrades gracefully at scale and the other doesn't — that difference is invisible on small test inputs and very visible in production. Practice deriving complexity from code directly: count nested loops, recognize when a hash-map lookup turns an O(n) search into O(1), and learn to spot the common complexity classes (O(1), O(log n), O(n), O(n log n), O(n²)) on sight."),
    chapter("algorithms-deep-dive", 2, "Sorting Algorithms", "Order from chaos", "Comparison sorts top out at O(n log n) — merge sort and quicksort both hit that bound through different strategies, divide-and-conquer either way.", ["Merge Sort", "Quicksort", "Divide & Conquer"], "Merge sort splits the array in half recursively until each piece has one element, then merges sorted halves back together — stable and always O(n log n), at the cost of needing extra memory for the merge step. Quicksort picks a pivot, partitions everything smaller to one side and larger to the other, then recurses on each side — average-case O(n log n) and in-place, but worst-case O(n²) on already-sorted or adversarial input if the pivot is chosen poorly. Both are the canonical examples of divide-and-conquer: break the problem into smaller versions of itself, solve those, combine the results."),
    chapter("algorithms-deep-dive", 3, "Searching & Binary Search", "Halving the problem", "Binary search finds a target in a sorted array in O(log n) by repeatedly eliminating half the remaining possibilities — one of the highest-leverage techniques in all of DSA.", ["Binary Search", "Sorted Arrays"], "On a sorted array, binary search checks the middle element, and based on whether the target is smaller or larger, throws away half the remaining search space — repeating until found or the space is empty. The implementation is famously easy to get subtly wrong (off-by-one errors in the boundary updates are notorious), so practice writing it from scratch until the loop invariant is automatic. Binary search also generalizes beyond literal sorted arrays: any problem where you can ask \"is this answer too big or too small\" and get a yes/no can often be binary-searched over the answer space itself."),
    chapter("algorithms-deep-dive", 4, "Dynamic Programming", "Don't recompute, remember", "DP solves problems with overlapping subproblems by caching results instead of recomputing them — turning exponential recursion into polynomial time.", ["Dynamic Programming", "Memoization", "Recursion"], "Dynamic programming applies when a problem breaks into overlapping subproblems — the same smaller computation gets needed repeatedly (naive recursive Fibonacci recomputes `fib(2)` thousands of times). Memoization caches each subproblem's result the first time it's computed (often with a dict keyed on the inputs) so repeats are O(1) lookups instead of full recomputation. Tabulation does the same thing bottom-up, filling a table iteratively instead of recursing top-down — usually faster in practice since it avoids call-stack overhead. Recognizing \"this problem has overlapping subproblems\" is the actual skill; the caching mechanics are simple once you see it."),
    chapter("algorithms-deep-dive", 5, "Greedy Algorithms & Backtracking", "Local choices, global answers", "Greedy algorithms make the locally-best choice at every step and hope it's globally optimal — it sometimes is, and proving when is half the problem.", ["Greedy", "Backtracking"], "A greedy algorithm makes whatever choice looks best right now, without reconsidering it later — it's fast and simple, but only correct for problems where local optimality actually implies global optimality (classic example: making change with standard coin denominations). Backtracking is the opposite instinct: try a choice, recurse, and if it leads to a dead end, undo it and try the next option — it's how you systematically explore all valid arrangements (permutations, N-Queens, Sudoku) without checking every possibility blindly, by pruning branches that can't possibly work as soon as that becomes clear."),
  ]
);

// ── Object-Oriented Design ────────────────────────────────────────────────────
const OOP_DESIGN_TRACK: Track = buildTrack(
  "object-oriented-design",
  "Object-Oriented Design",
  "Classes, interfaces, and the design principles that keep large codebases sane.",
  [
    chapter("object-oriented-design", 1, "Encapsulation & Abstraction", "Hiding the mess", "Good objects expose a small, clear interface and hide their internal mess behind it — callers shouldn't need to know how something works to use it correctly.", ["Encapsulation", "Abstraction"], "Encapsulation means an object controls access to its own internal state — instead of letting any code reach in and mutate a field directly, you expose methods that enforce the object's rules (a `BankAccount` exposes `withdraw()`, not a raw `balance` field anyone can set negative). Abstraction is the related idea one level up: a well-designed interface lets a caller use something correctly without knowing how it's implemented underneath — you call `.sort()` without knowing if it's quicksort or merge sort inside. Together they're what makes large codebases maintainable: implementation details can change without breaking every piece of code that depends on the interface."),
    chapter("object-oriented-design", 2, "Inheritance & Polymorphism", "Shared shape, different behavior", "Inheritance lets subclasses reuse a parent's code; polymorphism lets different subclasses respond to the same method call in their own way.", ["Inheritance", "Polymorphism"], "Inheritance lets a subclass reuse a parent class's fields and methods instead of duplicating them — `Dog` and `Cat` both inherit `name` and a default `make_sound()` from `Animal`. Polymorphism is what makes that useful in practice: code that calls `animal.make_sound()` doesn't need to know whether `animal` is actually a `Dog` or `Cat` — each subclass overrides the method with its own behavior, and the right one runs automatically. This is what lets you write a function once (`for a in animals: a.make_sound()`) that correctly handles every current and future subclass without modification."),
    chapter("object-oriented-design", 3, "Interfaces & Composition", "Favor composition over inheritance", "Deep inheritance chains get brittle fast. Composition — building objects out of smaller, swappable pieces — is usually the more flexible design.", ["Composition", "Interfaces"], "Deep inheritance hierarchies (a class inheriting from a class inheriting from a class) tend to get brittle: a change to a base class can ripple unpredictably through every descendant. Composition solves the same reuse problem differently — instead of a `FlyingCar` inheriting from both `Car` and `Plane` awkwardly, it *has* an `Engine` and a `Wing` as component objects it delegates to. Interfaces (or, in Python, duck typing — \"if it has a `.quack()` method, treat it like a duck\") define a contract multiple unrelated classes can fulfill, enabling polymorphism without forcing a shared inheritance chain at all."),
    chapter("object-oriented-design", 4, "SOLID Principles", "Five rules for sane design", "SOLID is five principles — Single Responsibility through Dependency Inversion — that describe what makes object-oriented code resist rotting as it grows.", ["SOLID", "Design Principles"], "SOLID is a set of five guidelines: Single Responsibility (a class should have one reason to change), Open/Closed (open for extension, closed for modification — add new behavior without editing existing working code), Liskov Substitution (a subclass should be usable anywhere its parent is, without surprises), Interface Segregation (many small, specific interfaces beat one giant one), and Dependency Inversion (depend on abstractions, not concrete implementations). None of these are laws — they're heuristics for the question \"will this design still be easy to change in six months,\" and the best way to internalize them is noticing which one you violated *after* a refactor gets painful."),
    chapter("object-oriented-design", 5, "Common Design Patterns", "Named solutions to recurring problems", "Design patterns are reusable solution shapes to problems that show up again and again — a shared vocabulary for talking about structure, not a checklist to apply everywhere.", ["Design Patterns", "Singleton", "Factory", "Observer"], "Design patterns are named, reusable solutions to problems that recur across many codebases — learning them gives you a shared vocabulary (\"just use a factory here\") more than a checklist to apply by default. The Singleton pattern ensures only one instance of something exists (a single shared config object); the Factory pattern centralizes object creation logic so callers don't need to know which concrete class to instantiate; the Observer pattern lets objects subscribe to and react to events on another object without tight coupling (this is the core idea behind most UI frameworks' event systems). Learn to recognize the *problem* each pattern solves before reaching for the pattern itself — applying one where it isn't needed adds complexity for nothing."),
  ]
);

// ── Databases & SQL ────────────────────────────────────────────────────────────
const DATABASES_TRACK: Track = buildTrack(
  "databases-and-sql",
  "Databases & SQL",
  "Relational thinking, queries, and how data actually gets stored.",
  [
    chapter("databases-and-sql", 1, "Tables, Rows & the Relational Model", "Data as tables", "A relational database stores data in tables with a fixed set of columns, and relationships between tables are expressed through keys, not nesting.", ["Tables", "Schema", "Keys"], "A relational database organizes data into tables, each row a record and each column a typed field — a `users` table, an `orders` table. A primary key uniquely identifies each row (usually an auto-incrementing `id`); a foreign key in one table references a primary key in another, expressing relationships (an `orders.user_id` points back to `users.id`) without duplicating the user's data into every order row. This normalized structure — storing each fact once and referencing it — is what prevents the data inconsistency bugs you get from copy-pasting the same information into multiple places."),
    chapter("databases-and-sql", 2, "SELECT, WHERE & Filtering", "Asking questions of your data", "`SELECT` is how you ask a database a question. Mastering `WHERE`, `ORDER BY`, and `LIMIT` covers the majority of queries you'll write day to day.", ["SELECT", "WHERE", "SQL Basics"], "`SELECT name, age FROM users WHERE age > 18 ORDER BY age DESC LIMIT 10` reads naturally once broken down: pick these columns, from this table, keep only rows matching this condition, sort them, and cap the result count. `WHERE` supports the same comparison and boolean logic as any programming language (`AND`, `OR`, `IN`, `LIKE` for pattern matching), and `NULL` requires special handling — `column = NULL` never matches anything; you need `IS NULL`. Get comfortable reading query results as a table, since that's the universal output shape for almost every database tool you'll touch."),
    chapter("databases-and-sql", 3, "JOINs", "Combining tables", "A JOIN combines rows from two tables based on a related column — it's how you turn `users` and `orders` into \"which user placed which order\" in one query.", ["JOIN", "Inner/Outer Join"], "An `INNER JOIN` returns rows where the join condition matches in both tables — `users JOIN orders ON users.id = orders.user_id` gives you one row per order, with the matching user's data attached. A `LEFT JOIN` keeps every row from the left table even if there's no match on the right (useful for \"all users, including ones with zero orders\" — the order columns come back `NULL` for those). JOINs are where most real-world query bugs live: an unintentional one-to-many relationship silently duplicates rows, so always sanity-check row counts before and after adding a join."),
    chapter("databases-and-sql", 4, "Aggregation & GROUP BY", "Summarizing data", "COUNT, SUM, AVG and GROUP BY turn thousands of rows into the handful of summary numbers a dashboard or report actually needs.", ["GROUP BY", "Aggregate Functions"], "Aggregate functions collapse many rows into one number: `COUNT(*)` counts rows, `SUM(price)` totals a column, `AVG(age)` averages it. On their own they summarize the whole table; `GROUP BY category` runs the same aggregation separately for each distinct value of `category`, which is how \"total sales per region\" or \"average score per student\" queries get written. `HAVING` filters groups *after* aggregation (e.g. only categories with more than 10 orders) — distinct from `WHERE`, which filters rows *before* grouping happens. This combination is the backbone of virtually every analytics dashboard."),
    chapter("databases-and-sql", 5, "Indexes & Why Queries Get Slow", "Reading without scanning everything", "Without an index, a query that filters on a column scans every row. An index lets the database jump straight to matching rows — at the cost of slower writes.", ["Indexes", "Query Performance"], "Without an index, `WHERE email = '...'` forces the database to check every single row — a full table scan, fine on a thousand rows, painfully slow on ten million. An index on `email` builds a sorted structure (typically a B-tree) the database can binary-search instead, turning that lookup from O(n) to roughly O(log n). The trade-off: every index has to be updated on every insert/update/delete, so indexing every column \"just in case\" slows down writes for marginal read benefit. The practical skill is identifying which columns are actually filtered or joined on frequently — those are the ones worth indexing."),
  ]
);

// ── Systems & OS Basics ────────────────────────────────────────────────────────
const SYSTEMS_TRACK: Track = buildTrack(
  "systems-and-os-basics",
  "Systems & OS Basics",
  "Processes, memory, and what the operating system is actually doing for you.",
  [
    chapter("systems-and-os-basics", 1, "Processes & Threads", "What's actually running", "A process is a running program with its own memory space; threads share that memory and run concurrently within it — the difference shapes how bugs (and speedups) happen.", ["Processes", "Threads", "Concurrency"], "A process is an instance of a running program, with its own isolated memory space — one process can't accidentally corrupt another's memory, which is why a crashing app usually doesn't take down your whole machine. Threads live inside a process and share its memory, which makes communication between them cheap but also means two threads can race to modify the same variable at once (a race condition) if you're not careful. Learn the difference between concurrency (multiple tasks making progress, possibly by interleaving on one core) and parallelism (multiple tasks literally running at the same instant on multiple cores) — they're related but not the same thing."),
    chapter("systems-and-os-basics", 2, "Memory: Stack vs. Heap", "Where your variables actually live", "The stack holds function-call-local data and is cleaned up automatically; the heap holds longer-lived data you (or a garbage collector) manage explicitly.", ["Stack", "Heap", "Memory Management"], "Local variables inside a function live on the stack — a simple, fast, automatically-managed region that grows with each function call and shrinks when the function returns (this is also why infinite recursion eventually crashes with a \"stack overflow\"). Data that needs to outlive the function that created it — an object you return, a list a function builds up across many calls — gets allocated on the heap, a larger, slower, manually-or-garbage-collector-managed region. Languages like Python and JavaScript hide heap management behind automatic garbage collection; languages like C and Rust make you reason about it directly, which is faster but adds an entire category of bugs (use-after-free, memory leaks) that garbage-collected languages mostly eliminate."),
    chapter("systems-and-os-basics", 3, "The File System", "Files are just an abstraction", "A file system is the OS's abstraction over raw disk blocks — directories, permissions, and paths are all conventions layered on top of \"a sequence of bytes somewhere on disk.\"", ["File Systems", "Paths", "Permissions"], "Underneath, a disk is just a huge array of addressable blocks — the file system is the layer that turns that into the familiar concept of files, folders, and paths. A path like `/home/user/notes.txt` is a lookup chain through directories, each one a mapping from names to either more directories or actual file data. Permissions (read/write/execute, owner/group/other on Unix systems) control who can do what to a given file — understanding these is essential the first time a script fails with \"permission denied\" and the fix isn't obvious. File systems also handle the messy reality of crashes mid-write, which is why operations like renaming a file are typically atomic where simply overwriting it in place isn't."),
    chapter("systems-and-os-basics", 4, "Compilation vs. Interpretation", "How your code actually runs", "Compiled languages translate source code to machine code ahead of time; interpreted languages translate (and run) it on the fly. Most modern languages are some hybrid of both.", ["Compilers", "Interpreters", "Bytecode"], "A compiler (C, Rust, Go) translates your entire source file into machine code before the program ever runs — that upfront cost buys faster execution and catches many errors before runtime. An interpreter (classic Python, Ruby) reads and executes source code line by line as the program runs, which is more flexible (no separate build step) but generally slower. Most modern languages blur the line: Python actually compiles to bytecode first, then an interpreter runs that bytecode; JavaScript engines use JIT (just-in-time) compilation, compiling hot code paths to machine code while the program is already running. Knowing which model a language uses explains a lot about its performance characteristics and error-reporting style."),
    chapter("systems-and-os-basics", 5, "Concurrency Pitfalls: Race Conditions & Deadlocks", "When timing becomes a bug", "A race condition happens when two threads access shared data without coordination; a deadlock happens when they wait on each other forever. Both are notoriously hard to reproduce.", ["Race Conditions", "Deadlocks", "Locks"], "A race condition occurs when the correctness of a program depends on the precise timing of two or more threads — two threads both reading a counter, incrementing it, and writing it back can lose an update if they interleave badly, and the bug only shows up intermittently under load, which makes it brutal to debug. A lock (mutex) fixes this by letting only one thread touch the shared data at a time — but locks introduce their own failure mode: a deadlock, where thread A holds lock 1 and waits for lock 2, while thread B holds lock 2 and waits for lock 1, and neither ever proceeds. The standard defense against deadlocks is a simple discipline: always acquire multiple locks in the same global order, everywhere in the codebase."),
  ]
);

// ── Networking Basics ────────────────────────────────────────────────────────
const NETWORKING_TRACK: Track = buildTrack(
  "networking-basics",
  "Networking Basics",
  "How data actually travels from your browser to a server and back.",
  [
    chapter("networking-basics", 1, "IP Addresses, Ports & DNS", "Finding a machine on the internet", "An IP address identifies a machine; a port identifies which program on it; DNS is the phonebook that turns human-readable domain names into IP addresses.", ["IP", "DNS", "Ports"], "Every device on a network has an IP address — a numeric identifier (`192.0.2.1` for IPv4) that routers use to deliver packets to the right machine. A single machine can run many network services at once, so a port number (0–65535) identifies which specific program on that machine a connection is for — web servers conventionally listen on port 443 (HTTPS) or 80 (HTTP). DNS (Domain Name System) is the distributed lookup service that turns a domain name like `example.com` into the IP address actually needed to connect — without it, you'd need to memorize numeric addresses for every site you visit."),
    chapter("networking-basics", 2, "TCP/IP & How Packets Travel", "Breaking data into pieces", "Data sent over the internet is broken into packets, routed independently, and reassembled at the destination — TCP adds reliability guarantees on top of that unreliable process.", ["TCP", "IP", "Packets"], "Data sent across a network is broken into packets, each routed independently — they can take different paths and arrive out of order, or get dropped entirely. IP handles addressing and routing but makes no reliability guarantees at all. TCP sits on top of IP and adds exactly that: it numbers packets so they can be reassembled in the correct order, detects loss and retransmits missing packets, and establishes a connection (the \"three-way handshake\") before data flows. This is the trade-off behind why TCP is reliable but has overhead, while UDP (no ordering, no retransmission) is faster but used only where occasional loss is acceptable, like video calls."),
    chapter("networking-basics", 3, "HTTP Requests & Responses", "The web's actual protocol", "HTTP is a request/response protocol: a client sends a method and a path, the server replies with a status code and a body. Nearly everything on the web is built on this exchange.", ["HTTP", "REST", "Status Codes"], "An HTTP request has a method (`GET` to retrieve, `POST` to create, `PUT`/`PATCH` to update, `DELETE` to remove), a path, headers (metadata like content type or auth tokens), and optionally a body. The response carries a status code — `2xx` success, `3xx` redirect, `4xx` client error (you sent something wrong, like `404 Not Found`), `5xx` server error (something broke server-side) — plus its own headers and body. REST is just a convention for mapping these methods and paths onto resources predictably (`GET /users/5` reads user 5, `DELETE /users/5` removes it) — understanding this pattern makes almost any web API immediately readable without documentation."),
    chapter("networking-basics", 4, "HTTPS & Encryption Basics", "Why the lock icon matters", "HTTPS wraps HTTP in TLS encryption, so data traveling over the network can't be read or tampered with by anyone in between — even on untrusted networks.", ["HTTPS", "TLS", "Encryption"], "Plain HTTP sends data in cleartext — anyone on the same network (a coffee-shop wifi, a compromised router) can read or modify it in transit. HTTPS wraps the same HTTP traffic inside TLS encryption, negotiated through a handshake where the server proves its identity with a certificate (issued by a trusted certificate authority) and both sides agree on an encryption key used only for that session. The browser's lock icon means that handshake succeeded and the connection is encrypted and authenticated — it says nothing about whether the site itself is trustworthy, just that nobody between you and it can eavesdrop or tamper with the traffic."),
    chapter("networking-basics", 5, "APIs & Client-Server Architecture", "How apps actually talk to each other", "Most software today is a client (browser, mobile app) talking to a server over an API — understanding this split clarifies where your code actually runs and why.", ["APIs", "Client-Server", "JSON"], "Most applications split into a client (what runs on the user's device — a browser tab, a mobile app) and a server (what runs on shared infrastructure, holding the database and business logic) that communicate over an API, almost always exchanging JSON over HTTP today. The client can't be trusted — anyone can open dev tools and modify requests — so any rule that actually matters (can this user delete this post?) must be enforced on the server, never just hidden in client-side code. This split is also why the same backend can serve a web app, a mobile app, and a third-party integration simultaneously: they're all just different clients of the same API."),
  ]
);

// ── Git & Version Control ──────────────────────────────────────────────────────
const GIT_TRACK: Track = buildTrack(
  "git-and-version-control",
  "Git & Version Control",
  "Commits, branches, and the workflow that makes collaborative code possible.",
  [
    chapter("git-and-version-control", 1, "Commits & the Git Object Model", "A history you can trust", "A commit is a snapshot of your entire project at a point in time, linked to its parent — that chain of snapshots is your project's complete history.", ["Commits", "Git Basics"], "Unlike a simple \"save versions of one file\" tool, Git snapshots your entire project at every commit, and each commit points to its parent, forming a chain — that's your project's history, and it's why you can check out any past state exactly. `git add` stages changes (marks them for the next commit); `git commit` actually creates the snapshot with a message explaining why, not just what, changed. Get comfortable with `git status` and `git diff` as your default first move before any commit — knowing exactly what you're about to commit prevents the single most common Git mistake, committing something you didn't mean to."),
    chapter("git-and-version-control", 2, "Branching & Merging", "Parallel lines of work", "A branch is a movable pointer to a commit, letting you work on something without touching the main line of history until you're ready to merge it back in.", ["Branches", "Merging"], "A branch is just a lightweight, movable pointer to a commit — creating one (`git branch feature-x` or `git checkout -b feature-x`) costs almost nothing, which is why Git workflows encourage branching constantly for any new piece of work. Merging brings two branches' histories back together; Git does this automatically when changes don't overlap, and asks you to resolve a conflict by hand when two branches changed the same lines differently. Understanding merge conflicts as \"Git genuinely can't guess which change you want\" rather than \"something broke\" makes them far less stressful to resolve — they're a normal, expected part of collaborative work."),
    chapter("git-and-version-control", 3, "Remotes, Push & Pull", "Syncing with everyone else", "Your local repository is a complete copy of the project history. A remote (like GitHub) is just another copy you push to and pull from to stay in sync with collaborators.", ["Remotes", "Push", "Pull"], "A remote is simply another copy of the repository — typically hosted on GitHub, GitLab, or similar — that you `push` your local commits to and `pull` others' commits from. Every clone of a Git repository has the *entire* history, not just the latest snapshot, which is why Git works perfectly fine offline and is genuinely distributed, unlike older centralized version control systems. `git fetch` downloads remote changes without merging them into your current branch (a safe way to see what's new); `git pull` is effectively `fetch` plus an automatic merge, which is convenient but can surprise you with an unexpected merge commit if you're not paying attention."),
    chapter("git-and-version-control", 4, "Pull Requests & Code Review", "How teams actually ship code", "A pull request proposes merging one branch into another and gives the team a place to review the diff before it lands — the real unit of collaboration on most teams.", ["Pull Requests", "Code Review"], "A pull request (PR) isn't a Git concept itself — it's a feature hosting platforms like GitHub layer on top of branches: \"here's a branch with my changes, please review and merge it into main.\" The PR page shows the full diff, lets teammates leave inline comments, and typically gates merging behind required checks (tests passing, at least one approval). Writing a good PR description — what changed and why, not just what — is a skill in itself, and is usually the deciding factor in how fast a review actually happens, since reviewers without context have to reverse-engineer intent from the diff alone."),
    chapter("git-and-version-control", 5, "Undoing Mistakes Safely", "Git is more forgiving than it feels", "Almost every Git mistake is recoverable — the trick is knowing the difference between commands that rewrite history (dangerous) and ones that don't (safe).", ["git reset", "git revert", "Recovery"], "`git revert` creates a *new* commit that undoes a previous one — it's safe to use on shared history because nothing already pushed gets rewritten, just added to. `git reset` actually moves your branch pointer and can discard commits or working-tree changes depending on the flag (`--soft`, `--mixed`, `--hard`) — powerful, but dangerous on anything already pushed and shared, since it rewrites history other people may have already built on top of. The single most useful safety net to know about is `git reflog`, which records every place your branch pointer has ever been — even after a bad `reset --hard`, the old commit is almost always still recoverable through it for a while."),
  ]
);

// ── Security Fundamentals ──────────────────────────────────────────────────────
const SECURITY_TRACK: Track = buildTrack(
  "security-fundamentals",
  "Security Fundamentals",
  "The handful of vulnerability classes responsible for most real-world breaches.",
  [
    chapter("security-fundamentals", 1, "Injection Attacks (SQL & Command)", "Never trust input", "Injection attacks happen when untrusted input gets interpreted as code instead of data — the fix is almost always the same: never build queries or commands by string concatenation.", ["SQL Injection", "Input Validation"], "SQL injection happens when user input gets concatenated directly into a query string — `\"SELECT * FROM users WHERE name = '\" + input + \"'\"` lets an attacker supply `input` that closes the string early and appends their own SQL, potentially reading or deleting the entire database. The fix is parameterized queries (prepared statements), where the input is passed separately from the query structure and the database driver handles escaping correctly — never string concatenation, no matter how carefully you think you've sanitized it. The same root cause (untrusted input treated as code) shows up in command injection (shelling out with unsanitized input) and is why the rule \"never trust input, never build commands by concatenation\" generalizes far beyond just SQL."),
    chapter("security-fundamentals", 2, "Cross-Site Scripting (XSS)", "When user content runs as code", "XSS happens when user-supplied content gets rendered as HTML/JavaScript instead of plain text, letting an attacker run their own script in another user's browser session.", ["XSS", "Sanitization"], "If a comment field's content gets inserted directly into the page as HTML (`innerHTML = userComment`) instead of as text, an attacker can submit `<script>...</script>` as their \"comment,\" and that script runs in every other visitor's browser with their full session privileges — stealing cookies, making authenticated requests on their behalf, defacing the page. Modern frameworks (React, Vue) escape content by default unless you explicitly opt out (`dangerouslySetInnerHTML` in React is named that way on purpose), which is the main reason XSS has gotten rarer — but any place raw HTML insertion is used deliberately needs careful sanitization of untrusted input first."),
    chapter("security-fundamentals", 3, "Authentication vs. Authorization", "Who you are vs. what you can do", "Authentication confirms identity; authorization decides what that identity is allowed to do. Conflating the two is one of the most common access-control bugs.", ["Auth", "Sessions", "Access Control"], "Authentication answers \"who is this\" — logging in with a password, an OAuth flow, a session token. Authorization answers a separate question — \"is this specific user allowed to do this specific thing\" — and it's a mistake to assume the second follows automatically from the first. A logged-in user being able to view `/orders/5` doesn't mean they should be able to view `/orders/6` just because the URL pattern is guessable — every endpoint that touches another user's data needs an explicit ownership check server-side, not just \"they're logged in so it's fine.\" This exact gap (broken object-level authorization) is consistently one of the most common real-world API vulnerabilities."),
    chapter("security-fundamentals", 4, "Secrets Management", "Keys don't belong in your codebase", "API keys, passwords, and tokens committed to source control are effectively public the moment they're pushed — even if the repo is later made private or the commit is deleted.", ["Secrets", "Environment Variables", "API Keys"], "A secret committed to Git history is compromised the moment it's pushed, full stop — deleting the file in a later commit doesn't remove it from history, and a private repo can still leak (a misconfigured permission, a fork, a screenshot in chat). Secrets belong in environment variables, loaded at runtime from a `.env` file kept out of version control (`.gitignore`'d) locally, and from a proper secrets manager in production — never hardcoded, never committed \"temporarily.\" If a secret does leak, rotating it (generating a new one and invalidating the old) is the only real fix; treating it as fine because \"the repo is private now\" is a common and costly mistake."),
    chapter("security-fundamentals", 5, "HTTPS, Hashing & Storing Passwords", "Never store a password in plain text", "Passwords should never be stored as plain text or even encrypted — they should be hashed with a slow, salted algorithm specifically designed to resist cracking.", ["Hashing", "bcrypt", "Salting"], "A password should never be stored in a retrievable form — not plain text, not even encrypted (since encryption is reversible with the right key). Instead it's hashed: run through a one-way function that produces a fixed-length output you can verify a guess against, but can't reverse back into the original password. Generic fast hashes (MD5, SHA-256) are actually the wrong tool here — they're fast specifically so attackers can brute-force billions of guesses per second once a database leaks. Purpose-built password hashing algorithms (bcrypt, argon2) are deliberately slow and automatically salt each password (add unique random data before hashing) so two identical passwords don't produce identical hashes, defeating precomputed lookup-table attacks."),
  ]
);

export const BUILTIN_TRACKS: Track[] = [
  PYTHON_FUNDAMENTALS_TRACK,
  PYTHON_FOR_AI_TRACK,
  WEB_FUNDAMENTALS_TRACK,
  DATA_STRUCTURES_TRACK,
  ALGORITHMS_TRACK,
  OOP_DESIGN_TRACK,
  DATABASES_TRACK,
  SYSTEMS_TRACK,
  NETWORKING_TRACK,
  GIT_TRACK,
  SECURITY_TRACK,
];

export function getBuiltinTrack(id: string): Track | undefined {
  return BUILTIN_TRACKS.find((t) => t.id === id);
}
